#!/usr/bin/env bash
set -euo pipefail

CODEX_HOME="${CODEX_HOME:-/home/codex/.codex}"
mkdir -p "${CODEX_HOME}"

CONFIG_FILE="${CODEX_HOME}/config.toml"
DEFAULT_MODEL="${CODEX_DEFAULT_MODEL:-gpt-5-codex}"
CUSTOM_API_KEY_ENV="${CODEX_CUSTOM_API_KEY_ENV:-CUSTOM_LLM_API_KEY}"

cat > "${CONFIG_FILE}" <<EOF
# Generated by containers/codex-cli/entrypoint.sh

model_provider = "openai"
model = "${DEFAULT_MODEL}"

[profiles.openai-login]
model_provider = "openai"
model = "${CODEX_OPENAI_MODEL:-$DEFAULT_MODEL}"

[profiles.custom-api]
model_provider = "custom_api"
model = "${CODEX_CUSTOM_API_MODEL:-$DEFAULT_MODEL}"
EOF

if [[ -n "${CODEX_CUSTOM_API_BASE_URL:-}" ]]; then
  cat >> "${CONFIG_FILE}" <<EOF

[model_providers.custom_api]
name = "Custom OpenAI-Compatible API"
base_url = "${CODEX_CUSTOM_API_BASE_URL}"
wire_api = "responses"
EOF

  if [[ -n "${CUSTOM_API_KEY_ENV}" && "${CUSTOM_API_KEY_ENV}" != "None" && "${CUSTOM_API_KEY_ENV}" != "none" ]]; then
    cat >> "${CONFIG_FILE}" <<EOF
env_key = "${CUSTOM_API_KEY_ENV}"
env_key_instructions = "Set ${CUSTOM_API_KEY_ENV} in the container environment"
EOF
  fi
fi

if [[ -n "${CODEX_CUSTOM_OPENAI_AUTH_BASE_URL:-}" ]]; then
  cat >> "${CONFIG_FILE}" <<EOF

[profiles.custom-openai-auth]
model_provider = "custom_openai_auth"
model = "${CODEX_CUSTOM_OPENAI_AUTH_MODEL:-$DEFAULT_MODEL}"

[model_providers.custom_openai_auth]
name = "Custom Provider Reusing OpenAI Auth"
base_url = "${CODEX_CUSTOM_OPENAI_AUTH_BASE_URL}"
wire_api = "responses"
requires_openai_auth = true
EOF
fi

exec "$@"
